[BGP-IPv6] Use metrics instead of weights for IPv6 routes
nmstate does not support ECPM with IPv6:
NmstateError: NotSupportedError: IPv6 ECMP route with weight is not supported yet